/*===================================================================*/
/*                                                                   */
/*  InfoNES_Mapper.c : Curated InfoNES Mapper set (BL616 build)       */
/*  AUTO-GENERATED by tools/gen_mapper.py -- do not edit by hand.     */
/*===================================================================*/

/*-------------------------------------------------------------------*/
/*  Include files                                                    */
/*-------------------------------------------------------------------*/

#include "InfoNES.h"
#include "InfoNES_System.h"
#include "InfoNES_Mapper.h"
#include "K6502.h"

/*-------------------------------------------------------------------*/
/*  Mapper resources                                                 */
/*-------------------------------------------------------------------*/

/* Disk System RAM (placed in PSRAM by NES_PSRAM_BSS in InfoNES.h) */
BYTE DRAM[ DRAM_SIZE ] NES_PSRAM_BSS;

/*-------------------------------------------------------------------*/
/*  Table of Mapper initialize function                              */
/*-------------------------------------------------------------------*/

struct MapperTable_tag MapperTable[] =
{
  {   0, Map0_Init },
  {   1, Map1_Init },
  {   2, Map2_Init },
  {   3, Map3_Init },
  {   4, Map4_Init },
  { -1, NULL }
};

/*-------------------------------------------------------------------*/
/*  body of Mapper functions                                         */
/*-------------------------------------------------------------------*/

#include "mapper/InfoNES_Mapper_000.c"
#include "mapper/InfoNES_Mapper_001.c"
#include "mapper/InfoNES_Mapper_002.c"
#include "mapper/InfoNES_Mapper_003.c"
#include "mapper/InfoNES_Mapper_004.c"

/* End of InfoNES_Mapper.c */
