#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate nes/infones_core/InfoNES_Mapper.c with a CURATED mapper set.

full InfoNES mapper set is built in (auto-discovered from the mapper directory
below). Measured: the 138 mapper files contribute only ~20.5 KB of static arrays
total, largest single file 8 KB; the real SRAM consumers (frame buffer / PPU /
SRAM / DRAM 40 KB in PSRAM) are core-shared and independent of mapper count. So
building all mappers adds ~0 SRAM -- trust the linker .map for the real budget.
The MapperTable[] entries and the #include list are generated from the SAME
auto-discovered list so they can never drift.

Re-run to regenerate after changing the mapper directory:
    python3 tools/gen_mapper.py
"""
import os
import re
import glob

# Auto-discover every InfoNES_Mapper_*.c in nes/infones_core/mapper/ so we never
# miss or mistype a mapper number. Result is sorted and de-duplicated.
_MAPDIR = os.path.join(os.path.dirname(__file__), "..", "nes", "infones_core", "mapper")

def _discover_mappers():
    nums = []
    for fn in glob.glob(os.path.join(_MAPDIR, "InfoNES_Mapper_*.c")):
        m = re.search(r"InfoNES_Mapper_(\d+)\.c$", fn)
        if m:
            nums.append(int(m.group(1)))
    return sorted(set(nums))

# 当前编译进固件的完整 mapper 集合（全 138 个，自动发现）。
MAPPERS = _discover_mappers()

OUT = os.path.join(os.path.dirname(__file__), "..", "nes", "infones_core", "InfoNES_Mapper.c")


def main():
    lines = []
    lines.append("/*===================================================================*/")
    lines.append("/*                                                                   */")
    lines.append("/*  InfoNES_Mapper.c : Curated InfoNES Mapper set (BL616 build)       */")
    lines.append("/*  AUTO-GENERATED by tools/gen_mapper.py -- do not edit by hand.     */")
    lines.append("/*===================================================================*/")
    lines.append("")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("/*  Include files                                                    */")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("")
    lines.append('#include "InfoNES.h"')
    lines.append('#include "InfoNES_System.h"')
    lines.append('#include "InfoNES_Mapper.h"')
    lines.append('#include "K6502.h"')
    lines.append("")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("/*  Mapper resources                                                 */")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("")
    lines.append("/* Disk System RAM (placed in PSRAM by NES_PSRAM_BSS in InfoNES.h) */")
    lines.append("BYTE DRAM[ DRAM_SIZE ] NES_PSRAM_BSS;")
    lines.append("")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("/*  Table of Mapper initialize function                              */")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("")
    lines.append("struct MapperTable_tag MapperTable[] =")
    lines.append("{")
    for m in MAPPERS:
        lines.append("  { %3d, Map%d_Init }," % (m, m))
    lines.append("  { -1, NULL }")
    lines.append("};")
    lines.append("")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("/*  body of Mapper functions                                         */")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("")
    for m in MAPPERS:
        lines.append('#include "mapper/InfoNES_Mapper_%03d.c"' % m)
    lines.append("")
    lines.append("/* End of InfoNES_Mapper.c */")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("Wrote %s with %d mappers" % (os.path.normpath(OUT), len(MAPPERS)))


if __name__ == "__main__":
    main()
