#!/usr/bin/env python3
# Generate soft_mjpeg_tables.h from jpeg_head.c (verbatim, zero transcription).
import re, sys

SRC = r"C:/Users/lx/WorkBuddy/2026-07-22-11-23-28/bl618-nofrendo/main/jpeg_head.c"
OUT = r"D:/bouffalo_sdk/examples/cherryusb/uvc_uac_nes/nes/soft_mjpeg_tables.h"

with open(SRC) as f:
    txt = f.read()

def hex_array(name):
    m = re.search(name + r"\[\]\s*=\s*\{([^}]*)\}", txt, re.S)
    assert m, name
    toks = re.findall(r"0x[0-9A-Fa-f]+|\d+", m.group(1))
    return [int(t, 16) if t.lower().startswith("0x") else int(t) for t in toks]

qy = hex_array(r"tableQy")
quv = hex_array(r"tableQuv")
huff = hex_array(r"tableHuffman")

assert len(qy) == 64 and len(quv) == 64, (len(qy), len(quv))

def c_arr(name, vals, width=16):
    lines = []
    for i in range(0, len(vals), width):
        chunk = ", ".join(str(v) for v in vals[i:i+width])
        lines.append("    " + chunk + ",")
    return "static const uint8_t %s[%d] = {\n%s\n};" % (name, len(vals), "\n".join(lines))

header = (
    "/* soft_mjpeg_tables.h - JPEG quant + Huffman tables.\n"
    " * Verbatim from BL618 HW MJPEG path (jpeg_head.c) so the software\n"
    " * encoder produces MJPEG byte-compatible with that pipeline.\n"
    " * AUTO-GENERATED by tools/gen_tables.py - do not edit by hand. */\n"
    "#ifndef _SOFT_MJPEG_TABLES_H_\n#define _SOFT_MJPEG_TABLES_H_\n#include <stdint.h>\n\n"
    + c_arr("JPEG_QY", qy) + "\n\n" + c_arr("JPEG_QUV", quv) + "\n\n"
    + c_arr("JPEG_HUFFMAN_RAW", huff) + "\n\n"
    + "#define JPEG_HUFFMAN_RAW_LEN %d\n" % len(huff)
    + "\n#endif /* _SOFT_MJPEG_TABLES_H_ */\n"
)

with open(OUT, "w") as f:
    f.write(header)
print("wrote", OUT, "qy", len(qy), "quv", len(quv), "huff", len(huff))
