#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_menu_font.py - 为生成本地游戏启动菜单用的 16x16 1-bit 点阵字体。

为什么需要它: BL616 端要在 UVC 视频流里画出中文游戏列表（超级玛丽/双截龙...），
但固件里没有 CJK 字体。这里借助主机上的 Pillow + 系统中文字体（simhei 等）
把菜单用到的全部 Unicode 码点渲染成 16x16 单色点阵，打包成 C 头文件
nes/nes_menu_font.h，编译进固件。生成的字体只含"菜单真正会用到的字"，
体积很小（几十个汉字 ≈ 1KB）。

用法:
    python tools/gen_menu_font.py            # 写 nes/nes_menu_font.h
    python tools/gen_menu_font.py --dry-run  # 只在终端打印覆盖到的字，不写文件

注意: 若菜单里新增了中文串，记得把同样的串加进下面的 STRINGS，重跑本脚本。
"""
import os
import sys

from PIL import Image, ImageFont, ImageDraw

CELL = 16  # 字形边长（像素）

# 菜单实际会用到的全部字符串（必须和固件里写的完全一致，否则缺字）。
# 包含: 标题、各游戏名、提示、空态，以及显式列出需要的 ASCII（>/A/S/T/R/E/F/1..）。
STRINGS = [
    "游戏列表",
    "↑↓ 选择   A/START 开始",
    "未找到游戏 请先烧录ROM",
    "超级玛丽", "坦克大战", "双截龙", "魂斗罗", "F1赛车", "炸弹人", "马戏团",
    "公路追逐赛", "2048",
    ">", "/", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
    "A", "S", "T", "R", "E", "F",
]

FONT_CANDIDATES = [
    r"C:/Windows/Fonts/simhei.ttf",
    r"C:/Windows/Fonts/msyh.ttc",
    r"C:/Windows/Fonts/simsun.ttc",
    r"C:/Windows/Fonts/simsunb.ttf",
]


def find_font():
    for p in FONT_CANDIDATES:
        if os.path.isfile(p):
            return p
    return None


def collect_codepoints(strings):
    cps = set()
    for s in strings:
        for ch in s:  # Python str 按码点迭代
            cps.add(ord(ch))
    return sorted(cps)


def render_glyph(font, cp):
    """渲染单个码点为 16x16 1-bit 点阵，返回 32 字节（行优先，MSB 在前）。"""
    img = Image.new("L", (CELL, CELL), 255)  # 白底
    d = ImageDraw.Draw(img)
    ch = chr(cp)
    # 先用 textbbox 取得字形包围盒，居中绘制
    bbox = d.textbbox((0, 0), ch, font=font)
    gw = max(1, bbox[2] - bbox[0])
    gh = max(1, bbox[3] - bbox[1])
    x = (CELL - gw) // 2 - bbox[0]
    y = (CELL - gh) // 2 - bbox[1]
    d.text((x, y), ch, font=font, fill=0)  # 黑字
    bits = bytearray(CELL * CELL // 8)
    px = img.load()
    for yy in range(CELL):
        for xx in range(CELL):
            if px[xx, yy] < 128:  # 黑 = 笔画
                bit = yy * CELL + xx
                bits[bit // 8] |= (0x80 >> (bit % 8))
    return bytes(bits)


def scan_rom_names():
    """扫描 tools/roms/*.nes，把文件名（去 .nes）作为额外串，避免漏字。"""
    names = []
    rom_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "roms")
    if os.path.isdir(rom_dir):
        for f in sorted(os.listdir(rom_dir)):
            if f.lower().endswith(".nes"):
                names.append(os.path.splitext(f)[0])
    return names


def main():
    dry_run = "--dry-run" in sys.argv
    fp = find_font()
    if not fp:
        sys.stderr.write("ERROR: 未找到中文字体（simhei/msyh/simsun）。\n")
        sys.exit(1)
    try:
        font = ImageFont.truetype(fp, 15)
    except Exception as e:  # .ttc 需要 index
        font = ImageFont.truetype(fp, 15, index=0)

    all_strings = list(STRINGS) + scan_rom_names()
    cps = collect_codepoints(all_strings)
    glyphs = [(cp, render_glyph(font, cp)) for cp in cps]

    if dry_run:
        names = [chr(c) for c, _ in glyphs]
        print("覆盖码点 %d 个: %s" % (len(glyphs), " ".join(names)))
        return

    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "nes")
    out_path = os.path.join(out_dir, "nes_menu_font.h")
    out_path = os.path.abspath(out_path)

    lines = []
    lines.append("/* Auto-generated by tools/gen_menu_font.py -- DO NOT EDIT. */")
    lines.append("/* 16x16 1-bit packed font (MSB-first, row-major) for the NES launcher menu. */")
    lines.append("#ifndef NES_MENU_FONT_H")
    lines.append("#define NES_MENU_FONT_H")
    lines.append("")
    lines.append("#define MENU_FONT_W  %d" % CELL)
    lines.append("#define MENU_FONT_H  %d" % CELL)
    lines.append("#define MENU_FONT_BPL (%d / 8)  /* bytes per line */" % CELL)
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    uint32_t cp;")
    lines.append("    const uint8_t bits[MENU_FONT_W * MENU_FONT_H / 8];")
    lines.append("} menu_glyph_t;")
    lines.append("")
    lines.append("static const menu_glyph_t g_menu_font[] = {")
    for cp, bits in glyphs:
        hexbytes = ", ".join("0x%02x" % b for b in bits)
        lines.append("    { 0x%04X, { %s } }," % (cp, hexbytes))
    lines.append("};")
    lines.append("")
    lines.append("#define MENU_FONT_COUNT ((int)(sizeof(g_menu_font) / sizeof(g_menu_font[0])))")
    lines.append("")
    lines.append("/* 线性查找码点对应的点阵；找不到返回 NULL。 */")
    lines.append("static inline const uint8_t *menu_glyph_bits(uint32_t cp)")
    lines.append("{")
    lines.append("    for (int i = 0; i < MENU_FONT_COUNT; i++) {")
    lines.append("        if (g_menu_font[i].cp == cp) return g_menu_font[i].bits;")
    lines.append("    }")
    lines.append("    return NULL;")
    lines.append("}")
    lines.append("")
    lines.append("#endif /* NES_MENU_FONT_H */")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("已生成 %s （%d 个字形，%.2f KB）" %
          (out_path, len(glyphs), len(glyphs) * (CELL * CELL // 8) / 1024.0))


if __name__ == "__main__":
    main()
