#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate nes/infones_core/InfoNES_Mapper.c with a CURATED mapper set.

BL616 has only ~414 KB SRAM, but the full InfoNES mapper table pulls in
~413 KB of static mapper state (138 mappers). We therefore compile only a
curated subset of the most common mappers. The MapperTable[] entries and
the #include list are generated from the SAME list so they can never drift.

To support more games later, just add mapper numbers to MAPPERS and re-run:
    python3 tools/gen_mapper.py
"""
import os

# Curated NES mappers. The embedded demo ROM (nes_rom.c) is NROM = mapper 0,
# which needs NO extra static RAM, so we compile ONLY mapper 0. The full 96-mapper
# set pulled in ~320 KB of static mapper state (one mapper carries a 256 KB buffer)
# that overflowed BL616's 415 KB SRAM. To support other ROMs later, add their mapper
# numbers here AND verify the SRAM budget (mapper static RAM currently lives in SRAM,
# not PSRAM) -- each mapper can add several KB.
# Current set supports:
#   0 (NROM: 超级玛丽/坦克大战/炸弹人/马戏团/2048)
#   1 (MMC1)
#   2 (UNROM: 魂斗罗 Contra)
#   3 (CNROM: 公路追逐赛)
#   4 (MMC3: 双截龙 Double Dragon / 超级玛丽3 等大量游戏)
# Mapper 3/4 are small-state mappers (no large WRAM/CHR-RAM buffer), safe for
# BL616 SRAM budget. If a game needs another mapper, add it here and rebuild.
MAPPERS = [0, 1, 2, 3, 4]

OUT = os.path.join(os.path.dirname(__file__), "..", "nes", "infones_core", "InfoNES_Mapper.c")


def main():
    lines = []
    lines.append("/*===================================================================*/")
    lines.append("/*                                                                   */")
    lines.append("/*  InfoNES_Mapper.c : Curated InfoNES Mapper set (BL616 build)       */")
    lines.append("/*  AUTO-GENERATED by tools/gen_mapper.py -- do not edit by hand.     */")
    lines.append("/*===================================================================*/")
    lines.append("")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("/*  Include files                                                    */")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("")
    lines.append('#include "InfoNES.h"')
    lines.append('#include "InfoNES_System.h"')
    lines.append('#include "InfoNES_Mapper.h"')
    lines.append('#include "K6502.h"')
    lines.append("")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("/*  Mapper resources                                                 */")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("")
    lines.append("/* Disk System RAM (placed in PSRAM by NES_PSRAM_BSS in InfoNES.h) */")
    lines.append("BYTE DRAM[ DRAM_SIZE ] NES_PSRAM_BSS;")
    lines.append("")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("/*  Table of Mapper initialize function                              */")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("")
    lines.append("struct MapperTable_tag MapperTable[] =")
    lines.append("{")
    for m in MAPPERS:
        lines.append("  { %3d, Map%d_Init }," % (m, m))
    lines.append("  { -1, NULL }")
    lines.append("};")
    lines.append("")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("/*  body of Mapper functions                                         */")
    lines.append("/*-------------------------------------------------------------------*/")
    lines.append("")
    for m in MAPPERS:
        lines.append('#include "mapper/InfoNES_Mapper_%03d.c"' % m)
    lines.append("")
    lines.append("/* End of InfoNES_Mapper.c */")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("Wrote %s with %d mappers" % (os.path.normpath(OUT), len(MAPPERS)))


if __name__ == "__main__":
    main()
