#!/usr/bin/env python3
"""Generate nes/infones_core/nes_rom.c: a minimal but VALID NROM (mapper 0)
ROM that makes the PPU render a solid color, used to smoke-test the
UVC+UAC + InfoNES pipeline on BL616 without a real game.

Also serves as the canonical example for tools/nes2c.py (convert any .nes).
"""
import os

# --- iNES header: "NES\x1a", PRG=1 (16KB), CHR=1 (8KB), mapper 0, no trainer ---
HEADER = bytes([0x4E, 0x45, 0x53, 0x1A, 0x01, 0x01, 0x00, 0x00]) + b"\x00" * 8

# --- 6502 program (16KB NROM: PRG loaded at CPU $8000, mirrored to $C000) ---
# For 16KB PRG the reset vector ($FFFC) lives at PRG file offset $3FFC and
# the code placed at CPU $C000 == PRG offset 0 (via the $C000-$FFFF mirror).
#   SEI / CLD
#   LDA #0 ; STA $2000 (PPU ctrl) ; STA $2001 (PPU mask, rendering off)
#   LDA #$3F ; STA $2006 ; LDA #0 ; STA $2006   (PPU addr -> $3F00 palette)
#   LDA #$15 ; STA $2007                            (palette entry 0 = color)
#   LDA #$1E ; STA $2001                            (enable BG + sprites)
#   JMP $C01E                                       (idle loop)
PROG = bytes([
    0x78,              # $C000 (PRG off 0) SEI
    0xD8,              # $C001 CLD
    0xA9, 0x00,        # $C002 LDA #0
    0x8D, 0x00, 0x20,  # $C004 STA $2000
    0x8D, 0x01, 0x20,  # $C007 STA $2001
    0xA9, 0x3F,        # $C00A LDA #$3F
    0x8D, 0x06, 0x20,  # $C00C STA $2006
    0xA9, 0x00,        # $C00F LDA #0
    0x8D, 0x06, 0x20,  # $C011 STA $2006
    0xA9, 0x15,        # $C014 LDA #$15
    0x8D, 0x07, 0x20,  # $C016 STA $2007
    0xA9, 0x1E,        # $C019 LDA #$1E
    0x8D, 0x01, 0x20,  # $C01B STA $2001
    0x4C, 0x1E, 0xC0,  # $C01E JMP $C01E (idle loop)
])

PRG_SIZE = 0x4000            # 16 KB
CHR_SIZE = 0x2000            # 8 KB

# PRG bank: zeros, program at offset 0 (CPU $C000), reset vector at $3FFC
prg = bytearray(PRG_SIZE)
assert len(PROG) <= PRG_SIZE
prg[0:len(PROG)] = PROG
prg[0x3FFC] = 0x00            # reset vector low  -> $C000
prg[0x3FFD] = 0xC0            # reset vector high

chr_rom = bytearray(CHR_SIZE)  # all-zero tiles -> tile 0 everywhere

rom = HEADER + bytes(prg) + bytes(chr_rom)

assert len(rom) == 16 + PRG_SIZE + CHR_SIZE, len(rom)

# --- emit C source ---
lines = []
lines.append("/* Auto-generated by tools/make_demo_rom.py - DO NOT EDIT. */")
lines.append("/* Minimal valid NROM (mapper 0) demo ROM: renders a solid color. */")
lines.append("#include <stdint.h>")
lines.append("")
lines.append("const unsigned char g_nes_rom[] = {")
for i in range(0, len(rom), 16):
    chunk = rom[i:i + 16]
    hexs = ", ".join("0x%02X" % b for b in chunk)
    comma = "," if i + 16 < len(rom) else ""
    lines.append("  " + hexs + comma)
lines.append("};")
lines.append("const uint32_t g_nes_rom_len = sizeof(g_nes_rom);")
lines.append("")

out_dir = r"D:\bouffalo_sdk\examples\cherryusb\uvc_uac_nes\nes\infones_core"
os.makedirs(out_dir, exist_ok=True)
with open(os.path.join(out_dir, "nes_rom.c"), "w") as f:
    f.write("\n".join(lines))

print("Wrote nes_rom.c :", len(rom), "bytes (header+16KB PRG+8KB CHR)")
