#!/usr/bin/env python3
"""Convert a .nes ROM file into nes/infones_core/nes_rom.c for embedding.

Usage:
    python tools/nes2c.py path/to/game.nes

Replace the auto-generated demo ROM with a real game, then rebuild the
BL616 firmware. The firmware reads g_nes_rom[] from flash (XIP) at runtime,
so no filesystem/SD card is required. For large ROMs (>~1 MB) check that
your board's flash partition has room.
"""
import os, sys

def main():
    if len(sys.argv) < 2:
        print("usage: nes2c.py <game.nes>")
        return 1
    src = sys.argv[1]
    with open(src, "rb") as f:
        rom = f.read()
    if rom[:4] != b"NES\x1a":
        print("error: not a valid iNES (.nes) file")
        return 1

    lines = []
    lines.append("/* Auto-generated by tools/nes2c.py from %s - DO NOT EDIT. */"
                 % os.path.basename(src))
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("const unsigned char g_nes_rom[] = {")
    for i in range(0, len(rom), 16):
        chunk = rom[i:i + 16]
        hexs = ", ".join("0x%02X" % b for b in chunk)
        comma = "," if i + 16 < len(rom) else ""
        lines.append("  " + hexs + comma)
    lines.append("};")
    lines.append("const uint32_t g_nes_rom_len = sizeof(g_nes_rom);")
    lines.append("")

    out = r"D:\bouffalo_sdk\examples\cherryusb\uvc_uac_nes\nes\infones_core\nes_rom.c"
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print("Wrote", out, ":", len(rom), "bytes")
    return 0

if __name__ == "__main__":
    sys.exit(main())
